import {
  amberDark,
  blueDark,
  bronzeDark,
  brownDark,
  crimsonDark,
  cyanDark,
  goldDark,
  grassDark,
  grayDark,
  greenDark,
  indigoDark,
  limeDark,
  mauveDark,
  mintDark,
  oliveDark,
  orangeDark,
  pinkDark,
  plumDark,
  purpleDark,
  redDark,
  sageDark,
  sandDark,
  skyDark,
  slateDark,
  tealDark,
  tomatoDark,
  violetDark,
  yellowDark,
} from "@radix-ui/colors";

import { theme } from "../stitches.config";

/**
 * @package
 */
export const dark = theme("dark", {
  colors: {
    ...amberDark,
    ...blueDark,
    ...bronzeDark,
    ...brownDark,
    ...crimsonDark,
    ...cyanDark,
    ...goldDark,
    ...grassDark,
    ...grayDark,
    ...greenDark,
    ...indigoDark,
    ...limeDark,
    ...mauveDark,
    ...mintDark,
    ...oliveDark,
    ...orangeDark,
    ...pinkDark,
    ...plumDark,
    ...purpleDark,
    ...redDark,
    ...sageDark,
    ...sandDark,
    ...skyDark,
    ...slateDark,
    ...tealDark,
    ...tomatoDark,
    ...violetDark,
    ...yellowDark,
  },
});
